title: my primery work
description: learning through doing
template:
  repo: my-primery-work-template
  name: my-primery-work
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
